src/SocialNetApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from users import views as uviews
from userposts import views as upviews


urlpatterns = [
    path('', upviews.home_page, name='home'),
    path('admin/', admin.site.urls),
    path('chat/', include('friendchat.urls')),
    path('friend/', include('friends.urls', namespace="friends")),
    path('login/', uviews.login_view, name="login"),
    path('logout/', uviews.logout_view, name="logout"),
    path('profile/', include('users.urls', namespace="profile")),
    path('register/', uviews.registration_view, name="register"),
    path('search/', uviews.user_search_view, name="search"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/friendchat/urls.py
from django.urls import path
from friendchat import views as fcviews
from django.conf.urls.static import static
from django.conf import settings

app_name = "friendchat"

urlpatterns = [
    path('', fcviews.chat_list_view, name="friend_chat_list"),
    path('<friend_id>/', fcviews.chat_view, name='friend_chat'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/friends/urls.py
from django.urls import path
from friends import views as fviews
from django.conf.urls.static import static
from django.conf import settings
from . import api

app_name = "friend_app"

urlpatterns = [
    path('accept_friend_request/<friend_request_id>/', fviews.accept_friend_request, name="accept_friend_request"),
    path('cancel_friend_request/', fviews.cancel_friend_request, name="cancel_friend_request"),
    path('decline_friend_request/<friend_request_id>/', fviews.decline_friend_request, name="decline_friend_request"),
    path('friend_list/<user_id>', fviews.friend_list_view, name="friend_list"),
    path('friend_request/', fviews.send_friend_request, name="friend_request"),
    path('friend_request/<user_id>/', fviews.friend_request_view, name="friend_request_list"),
    path('remove_friend/', fviews.remove_friend, name="remove_friend"),
    path('api/friendlist/<int:pk>/', api.FriendDetail.as_view(), name='friends_api'), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path
from users import views as uview
from django.conf.urls.static import static
from django.conf import settings
from . import api

app_name = "user_app"

urlpatterns = [
    path('<user_id>/', uview.profile_view, name="user_profile"),
    path('<user_id>/edit/', uview.edit_user_view, name="edit_user"),
    path('api/user/', api.CreateUser.as_view(), name='create_user_api'), 
    path('api/user/<int:pk>/', api.UserDetail.as_view(), name='user_detail_api'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/friends/models.py
from django.db import models
from django.conf import settings

class FriendList(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user")
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="friends")

    def __str__(self):
        return self.user.username

    def add_friend(self, user_to_add):
        if not user_to_add in self.friends.all():
            self.friends.add(user_to_add)
    
    def remove_friend(self, user_to_remove):
        if user_to_remove in self.friends.all():
            self.friends.remove(user_to_remove)

    def unfriend(self, user_to_remove):
        self.remove_friend(user_to_remove)

        removed_user = FriendList.objects.get(user=user_to_remove)
        removed_user.remove_friend(self.user)

    def is_mutual_friend(self, friend):
        if friend in self.friends.all():
            return True
        return False

class FriendRequest(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="receiver")
    pending = models.BooleanField(blank=True, null=False, default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender.username
    
    def accept(self):
        receiver_friends = FriendList.objects.get(user=self.receiver)
        if receiver_friends:
            receiver_friends.add_friend(self.sender)
            sender_friends = FriendList.objects.get(user=self.sender)
            sender_friends.add_friend(self.receiver)
            self.pending = False
            self.save()
    
    def decline(self):
        self.pending = False
        self.save()

    def cancel(self):
        self.pending = False
        self.save()

src/friends/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
import json
from users.models import User
from friends.models import FriendList, FriendRequest

def friend_request_view(request, *args, **kwargs):
    context = {}
    curr_user = request.user
    if curr_user.is_authenticated:
        user_id = kwargs.get("user_id")
        user = User.objects.get(pk=user_id)
        if user == curr_user:
            friend_requests = FriendRequest.objects.filter(receiver=user, pending=True)
            context['friend_requests'] = friend_requests
        else:
            return HttpResponse("You may only view your friend requests")
    else:
        redirect("login")
    return render(request, "friends/friend_requests.html", context)

def send_friend_request(request, *args, **kwargs):
    curr_user = request.user
    ajax_content = {}
    if request.method == "POST" and curr_user.is_authenticated:
        user_id = request.POST.get("receiver_user_id")
        if user_id:
            receiver = User.objects.get(pk=user_id)
            try:
                friend_requests = FriendRequest.objects.filter(sender=curr_user, receiver=receiver)
                try:
                    for f_request in friend_requests:
                        if f_request.pending:
                            raise Exception("Friend request already sent.")
                    friend_request = FriendRequest(sender=curr_user, receiver=receiver)
                    friend_request.save()
                    ajax_content['result'] = "success"
                    ajax_content['response'] = "Friend request sent"
                except Exception as e:
                    ajax_content['result'] = "error"
                    ajax_content['response'] = "An error occured. Failed to send request"
            except FriendRequest.DoesNotExist:
                friend_request = FriendRequest(sender=curr_user, receiver=receiver)
                friend_request.save()
                ajax_content['result'] = "success"
                ajax_content['response'] = "Friend request sent"
            if ajax_content["response"] == None:
                ajax_content['result'] = "error"
                ajax_content['response'] = "An error occured. Failed to send request"
        else:
            ajax_content['result'] = "error"
            ajax_content['response'] = "Something went wrong"
    else:
        ajax_content['result'] = "error"
        ajax_content['response'] = "You must be logged in to send a friend request"
    return HttpResponse(json.dumps(ajax_content), content_type="application/json")

def accept_friend_request(request, *args, **kwargs):
    curr_user = request.user
    ajax_content = {}
    if request.method == "GET" and curr_user.is_authenticated:
        friend_request_id = kwargs.get("friend_request_id")
        if friend_request_id:
            friend_request = FriendRequest.objects.get(pk=friend_request_id)
            if friend_request.receiver == curr_user:
                if friend_request:
                    friend_request.accept()
                    ajax_content['result'] = "success"
                    ajax_content['response'] = "Friend request accepted"
                else:
                    ajax_content['result'] = "error"
                    ajax_content['response'] = "An error occurred. Failed to decline request"
            else:
                ajax_content['result'] = "error"
                ajax_content["response"] = "You may only accept your own friend requests"
        else:
            ajax_content['result'] = "error"
            ajax_content["response"] = "No friend request of such id found"
    else:
        ajax_content['result'] = "error"
        ajax_content["response"] = "You must be logged in to accept a friend request"
    return HttpResponse(json.dumps(ajax_content), content_type="application/json")

def decline_friend_request(request, *args, **kwargs):
    curr_user = request.user
    ajax_content = {}
    if request.method == "GET" and curr_user.is_authenticated:
        friend_request_id = kwargs.get("friend_request_id")
        if friend_request_id:
            friend_request = FriendRequest.objects.get(pk=friend_request_id)
            if friend_request.receiver == curr_user:
                if friend_request:
                    friend_request.decline()
                    ajax_content['result'] = "success"
                    ajax_content['response'] = "Friend request declined"
                else:
                    ajax_content['result'] = "error"
                    ajax_content['response'] = "An error occurred. Please try again later"
            else:
                ajax_content['result'] = "error"
                ajax_content['response'] = "You may only decline requests that you received"
        else:
            ajax_content['result'] = "error"
            ajax_content['response'] = "No friend request of such id found"
    else:
        ajax_content['result'] = "error"
        ajax_content['response'] = "You must be logged in to decline a friend request"
    return HttpResponse(json.dumps(ajax_content), content_type="application/json")

def cancel_friend_request(request, *args, **kwargs):
    curr_user = request.user
    ajax_content = {}
    if request.method == "POST" and curr_user.is_authenticated:
        user_id = request.POST.get("receiver_user_id")
        if user_id:
            receiver = User.objects.get(pk=user_id)
            try:
                friend_requests_by_curr_user = FriendRequest.objects.filter(sender=curr_user, receiver=receiver, pending=True)
            except Exception as e:
                ajax_content['result'] = "error"
                ajax_content['response'] = "An error occurred. No friend requests to cancel"
            # should only have 1 such request as each user can only send 1 request to another specific user
            # however we should still check to ensure that all requests to that specific user is cancelled
            if len(friend_requests_by_curr_user) > 1:
                for request in friend_requests_by_curr_user:
                    request.cancel()
                ajax_content['result'] = "success"
                ajax_content['response'] = "Friend request cancelled"
            else:
                friend_requests_by_curr_user.first().cancel()
                ajax_content['result'] = "success"
                ajax_content['response'] = "Friend request cancelled"
        else:
            ajax_content['result'] = "error"
            ajax_content['response'] = "An error occurred. No user of such id found"
    else:
        ajax_content['result'] = "error"
        ajax_content['response'] = "You must be logged in to cancel a friend request"
    return HttpResponse(json.dumps(ajax_content), content_type="application/json")


def remove_friend(request, *args, **kwargs):
    user = request.user
    ajax_content = {}
    if request.method == "POST" and user.is_authenticated:
        user_id = request.POST.get("receiver_user_id")
        if user_id:
            try:
                user_to_remove = User.objects.get(pk=user_id)
                self_friend_list = FriendList.objects.get(user=user)
                self_friend_list.unfriend(user_to_remove)
                ajax_content['result'] = "success"
                ajax_content['response'] = "Friend removed successfully"
            except Exception as e:
                ajax_content['result'] = "error"
                ajax_content['response'] = "An error occurred. Failed to remove friend"
        else:
            ajax_content['result'] = "error"
            ajax_content['response'] = "Something went wrong. Unable to remove friend"
    else:
        ajax_content['result'] = "error"
        ajax_content['response'] = "You must be logged in to remove a friend"
    return HttpResponse(json.dumps(ajax_content), content_type="application/json")


def friend_list_view(request, *args, **kwargs):
    context = {}
    curr_user = request.user
    if curr_user.is_authenticated:
        viewed_user_id = kwargs.get("user_id")
        if viewed_user_id:
            try:
                viewed_user = User.objects.get(pk=viewed_user_id)
                context['curr_user_obj'] = viewed_user
            except User.DoesNotExist:
                return HttpResponse("User does not exist")
            try:
                viewed_friend_list = FriendList.objects.get(user=viewed_user)
            except FriendList.DoesNotExist:
                return HttpResponse("No friend list found")

            if curr_user != viewed_user:
                if not curr_user in viewed_friend_list.friends.all():
                    return HttpResponse("You may only view your own or your friends' friend list")
            
            curr_user_friend_list = FriendList.objects.get(user=curr_user)
            matched_friends = []
            for friend in viewed_friend_list.friends.all():
                matched_friends.append((friend, curr_user_friend_list.is_mutual_friend(friend)))
            context['matched_friends'] = matched_friends
    else:
        return HttpResponse("You must be logged in to view a user's friend list")
    return render(request, "friends/friend_list.html", context)

src/friends/templates/friends/accept_friend_request.html
<script type="text/javascript">
    function acceptFriendRequest(friend_request_id, uiUpdateFunction){        
        var url = "{% url 'friend_app:accept_friend_request' friend_request_id=417293055187147 %}".replace("417293055187147", friend_request_id)
        $.ajax({
            type: "GET",
            dataType: "json",
            url: url,
            timeout: 5000,
            success: function(data){
                if(data["result"] == "success"){

                }
                else if(data.result != null){
                    alert(data["response"])
                }
            },
            error: function(data){
                alert(data["response"])
            },
            complete: function(data){
                uiUpdateFunction()
            },
        });
    }
</script>

src/friends/templates/friends/cancel_friend_request.html
<script type="text/javascript">
    function cancelFriendRequest(id, uiUpdateFunction){        
        url = "{% url 'friend_app:cancel_friend_request' %}"
        ajax_content = {
            "csrfmiddlewaretoken": "{{ csrf_token }}",
            "receiver_user_id": id,
        }
        $.ajax({
            type: "POST",
            dataType: "json",
            url: url,
            data: ajax_content,
            timeout: 5000,
            success: function(data){
                if(data["result"] == "success"){

                }
                else if(data.result != null){
                    alert(data["response"])
                }
            },
            error: function(data){
                alert(data["response"])
            },
            complete: function(data){
                uiUpdateFunction()
            },
        });
    }

</script>

src/friends/templates/friends/decline_friend_request.html
<script type="text/javascript">
    function declineFriendRequest(friend_request_id, uiUpdateFunction){
        var url = "{% url 'friend_app:decline_friend_request' friend_request_id=417293055187147 %}".replace("417293055187147", friend_request_id)
        $.ajax({
            type: "GET",
            dataType: "json",
            url: url,
            timeout: 5000,
            success: function(data){
                if(data["result"] == "success"){

                }
                else if(data.result != null){
                    alert(data["response"])
                }
            },
            error: function(data){
                alert(data["response"])
            },
            complete: function(data){
                uiUpdateFunction()
            },
        });
    }
</script>

src/friends/templates/friends/friend_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.friends-text{
		color: #000;
		font-weight: 500;
	}
	.friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
</style>

<div class="container">
	<div class="card d-flex flex-column flex-grow-1 p-2">

		{% if matched_friends %}
		{% for friend in matched_friends %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<a class="profile-link" href="{% url 'user_app:user_profile' user_id=friend.0.pk %}">
				<div class="card-image m-2">
					<img class="img-fluid profile-image" src="{{friend.0.profile_image.url}}" alt="">
				</div>
			</a>
			
			<div class="card-center px-2">
				<a class="profile-link" href="{% url 'user_app:user_profile' user_id=friend.0.pk %}">
					<h4 class="card-title">{{friend.0.username|truncatechars:50}}</h4>
				</a>
				{% if friend.1 %}
				<a href="{% url 'friendchat:friend_chat' friend_id=friend.0.pk %}">Send a Message</a>
				{% endif %}
				
			</div>
			
			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
				{% if friend.1 %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							Friends 
						</p>
						<span class="material-icons checkmark-icon m-auto pl-2">
						check_circle_outline
						</span>
					</div>
				{% else %}
					{% if friend.0 !=  request.user %}
						<div class="d-flex flex-row friends-text-container p-3">
							<p class="friends-text m-auto">
								Not Friends 
							</p>
							<span class="material-icons cancel-icon m-auto pl-2">cancel</span>
						</div>
					{% endif %}
				{% endif %}
				{% if friend.0 == request.user %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							This is you 
						</p>
						<span class="material-icons m-auto pl-2">
						person_pin
						</span>
					</div>
				{% endif %}
			</div>
		</div>
		
		{% endfor %}
		
		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No friends</p>
		</div>
		{% endif %}
	</div>
	
</div>

{% endblock content %}

src/friends/templates/friends/friend_requests.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<style type="text/css">
	.profile-image{
		max-height: 50px;
		max-width: 50px;
        min-height: 50px;
        min-width: 50px;
        border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.confirm-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request:hover {
		opacity: 0.3;
	}
</style>

<div class="container">
	<div class="card p-2">
		{% if friend_requests %}
		{% for request in friend_requests %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<a class="profile-link" href="{% url 'user_app:user_profile' user_id=request.sender.id %}">
				<div class="card-image m-2">
					<img class="img-fluid profile-image" src="{{request.sender.profile_img.url}}" alt="">
				</div>
			</a>
			<a class="profile-link" href="{% url 'user_app:user_profile' user_id=request.sender.id %}">
				<div class="card-center px-2">
					<h4 class="card-title">{{request.sender.username}}</h4>
				</div>
			</a>
			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
	  			<span id="id_cancel_{{request.sender.id}}" class="decline-friend-request material-icons p-1" onclick='triggerDeclineFriendRequest("{{request.id}}")'>cancel</span>
	  			<span id="id_confirm_{{request.sender.id}}" class="confirm-friend-request material-icons p-1" onclick='triggerAcceptFriendRequest("{{request.id}}")'>check</span>
			</div>
		</div>
		{% endfor %}
		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No friend requests</p>
		</div>
		{% endif %}
		</div>
	</div>
	
</div>

<script type="text/javascript">

	function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}

	function triggerAcceptFriendRequest(friend_request_id){
		acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}
</script>

{% include 'friends/accept_friend_request.html' %}
{% include 'friends/decline_friend_request.html' %}


{% endblock content %}

src/friends/templates/friends/remove_friend.html
<script type="text/javascript">
    function removeFriend(id, uiUpdateFunction){
        url = "{% url 'friend_app:remove_friend' %}"
        ajax_content = {
            "csrfmiddlewaretoken": "{{ csrf_token }}",
            "receiver_user_id": id,
        }
        $.ajax({
            type: "POST",
            dataType: "json",
            url: url,
            data: ajax_content,
            timeout: 5000,
            success: function(data){
                if(data["result"] == "success"){

                }
                else if(data.result != null){
                    alert(data["response"])
                }
            },
            error: function(data){
                alert(data["response"])
            },
            complete: function(data){
                uiUpdateFunction()
            },
        });
    }
</script>

src/friends/templates/friends/send_friend_request.html
<script type="text/javascript">
    function sendFriendRequest(id, uiUpdateFunction){
        ajax_content = {
            "csrfmiddlewaretoken": "{{ csrf_token }}",
            "receiver_user_id": id,
        }
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "{% url 'friend_app:friend_request' %}",
            timeout: 5000,
            data: ajax_content,
            success: function(data){
                console.log("success: " + data)
                if (data["result"] == "success"){
                    // update ui
                } else if (data['response'] != null) {
                    alert(data["response"])
                }
            },
            error: function(data){
                alert(data["response"])
            },
            complete: function(data){
                uiUpdateFunction()
            },
        });
    }
</script>