src/SocialNetApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from users import views as uviews
from userposts import views as upviews


urlpatterns = [
    path('', upviews.home_page, name='home'),
    path('admin/', admin.site.urls),
    path('chat/', include('friendchat.urls')),
    path('friend/', include('friends.urls', namespace="friends")),
    path('login/', uviews.login_view, name="login"),
    path('logout/', uviews.logout_view, name="logout"),
    path('profile/', include('users.urls', namespace="profile")),
    path('register/', uviews.registration_view, name="register"),
    path('search/', uviews.user_search_view, name="search"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/friendchat/urls.py
from django.urls import path
from friendchat import views as fcviews
from django.conf.urls.static import static
from django.conf import settings

app_name = "friendchat"

urlpatterns = [
    path('', fcviews.chat_list_view, name="friend_chat_list"),
    path('<friend_id>/', fcviews.chat_view, name='friend_chat'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/friends/urls.py
from django.urls import path
from friends import views as fviews
from django.conf.urls.static import static
from django.conf import settings
from . import api

app_name = "friend_app"

urlpatterns = [
    path('accept_friend_request/<friend_request_id>/', fviews.accept_friend_request, name="accept_friend_request"),
    path('cancel_friend_request/', fviews.cancel_friend_request, name="cancel_friend_request"),
    path('decline_friend_request/<friend_request_id>/', fviews.decline_friend_request, name="decline_friend_request"),
    path('friend_list/<user_id>', fviews.friend_list_view, name="friend_list"),
    path('friend_request/', fviews.send_friend_request, name="friend_request"),
    path('friend_request/<user_id>/', fviews.friend_request_view, name="friend_request_list"),
    path('remove_friend/', fviews.remove_friend, name="remove_friend"),
    path('api/friendlist/<int:pk>/', api.FriendDetail.as_view(), name='friends_api'), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path
from users import views as uview
from django.conf.urls.static import static
from django.conf import settings
from . import api

app_name = "user_app"

urlpatterns = [
    path('<user_id>/', uview.profile_view, name="user_profile"),
    path('<user_id>/edit/', uview.edit_user_view, name="edit_user"),
    path('api/user/', api.CreateUser.as_view(), name='create_user_api'), 
    path('api/user/<int:pk>/', api.UserDetail.as_view(), name='user_detail_api'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang=en>

<head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<script src="{% static 'bootstrap/js/jquery.js' %}"></script>
	<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
    	<title>SocialNetApp</title>
	{% include 'static/base_css.html' %} 
	{% include 'static/base_js.html' %}
</head>

<body>

{% include 'header.html' %} 

<div class="main">
	{% block content %}

	{% endblock content %}
</div>

{% include 'footer.html' %}

</body>
</html>

src/templates/footer.html
<div class="d-flex p-3 flex-row align-items-center footer bg-white shadow-lg mt-4">
    <p class="m-auto">Advanced Web Development Final Coursework</p>
</div>

src/templates/header.html
{% load static %}
<div class="d-flex p-3 bg-white border-bottom shadow-sm">
    <div class="d-md-flex flex-row flex-grow-1 align-items-center">
        <h5 class="font-weight-normal justify-content-start">
            <a class="p-1 logo-text" href="{% url 'home' %}">SocialNetApp</a>
        </h5>
        <form class="ml-4 search-bar justify-content-start" onsubmit="return executeQuery();">
            <input type="text" class="form-control" name="search_user" id="user_q" placeholder="Search User">
        </form>
        <div class="d-flex flex-row-reverse flex-grow-1">
            <nav>
                {% if request.user.is_authenticated %}
                    <div class="dropdown dropleft show p-2">
                        <div class="d-flex flex-row">
                            <!-- chats -->
                            <a class="rounded-circle mr-3" href="{% url 'friendchat:friend_chat_list' %}">
                                <span class="d-flex material-icons notifications-material-icon m-auto align-items-center" style="cursor: pointer;">chat_bubble_outline</span>
                            </a>
                            
                            <!-- friends -->
                            <a class="rounded-circle mr-3" href="{% url 'friend_app:friend_list' user_id=request.user.id %}">
                                <span class="d-flex material-icons notifications-material-icon m-auto align-items-center" style="cursor: pointer;">people_alt</span>
                            </a>

                            <!-- profile -->
                            <div class="btn-group dropleft">
                                <img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{request.user.profile_img.url}}" alt="default profile logo", style="cursor: pointer;">
                                <div class="dropdown-menu" aria-labelledby="id_profile_links">
                                    <!-- href notes: 'profile' comes from path name in SocialNetApp urls.py-->
                                    <!-- href notes: 'user_profile' comes from path name in users/urls.py-->
                                    <a class="dropdown-item" href="{% url 'profile:user_profile' user_id=request.user.id %}">Profile</a>
                                    <!-- <a class="dropdown-item" href="#">Settings</a> -->
                                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <a class="p-2 text-group-2" href="{% url 'login' %}">Login</a>
                    <a class="p-2 text-group-2" href="{% url 'register' %}">Register</a>
                {% endif %}
            </nav>
        </div>
    </div>
</div>

<script type="text/javascript">
    function executeQuery(){
        var query = document.getElementById("user_q").value;
        window.location.replace("{% url 'search' %}?q=" + query);
        return false;
    }
</script>