src/SocialNetApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from users import views as uviews
from userposts import views as upviews


urlpatterns = [
    path('', upviews.home_page, name='home'),
    path('admin/', admin.site.urls),
    path('chat/', include('friendchat.urls')),
    path('friend/', include('friends.urls', namespace="friends")),
    path('login/', uviews.login_view, name="login"),
    path('logout/', uviews.logout_view, name="logout"),
    path('profile/', include('users.urls', namespace="profile")),
    path('register/', uviews.registration_view, name="register"),
    path('search/', uviews.user_search_view, name="search"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/friendchat/urls.py
from django.urls import path
from friendchat import views as fcviews
from django.conf.urls.static import static
from django.conf import settings

app_name = "friendchat"

urlpatterns = [
    path('', fcviews.chat_list_view, name="friend_chat_list"),
    path('<friend_id>/', fcviews.chat_view, name='friend_chat'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/friends/urls.py
from django.urls import path
from friends import views as fviews
from django.conf.urls.static import static
from django.conf import settings
from . import api

app_name = "friend_app"

urlpatterns = [
    path('accept_friend_request/<friend_request_id>/', fviews.accept_friend_request, name="accept_friend_request"),
    path('cancel_friend_request/', fviews.cancel_friend_request, name="cancel_friend_request"),
    path('decline_friend_request/<friend_request_id>/', fviews.decline_friend_request, name="decline_friend_request"),
    path('friend_list/<user_id>', fviews.friend_list_view, name="friend_list"),
    path('friend_request/', fviews.send_friend_request, name="friend_request"),
    path('friend_request/<user_id>/', fviews.friend_request_view, name="friend_request_list"),
    path('remove_friend/', fviews.remove_friend, name="remove_friend"),
    path('api/friendlist/<int:pk>/', api.FriendDetail.as_view(), name='friends_api'), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path
from users import views as uview
from django.conf.urls.static import static
from django.conf import settings
from . import api

app_name = "user_app"

urlpatterns = [
    path('<user_id>/', uview.profile_view, name="user_profile"),
    path('<user_id>/edit/', uview.edit_user_view, name="edit_user"),
    path('api/user/', api.CreateUser.as_view(), name='create_user_api'), 
    path('api/user/<int:pk>/', api.UserDetail.as_view(), name='user_detail_api'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class UserManager(BaseUserManager):

    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("The email must not be empty.")
        if not username:
            raise ValueError("The username must not be empty.")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

def get_profile_image_path(self):
    return f'profile_images/{self.pk}/{"profile_img.png"}'

def get_default_profile_img():
    return "project_files/default_profile.png"

class User(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=40, unique=True)
    username = models.CharField(max_length=20, unique=True)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    profile_img = models.ImageField(max_length=255, upload_to=get_profile_image_path, null=True, blank=True, default=get_default_profile_img)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    # override defaults in AbstractBaseUser
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    # define which field to be used as username and which fields are required
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

    def get_profile_image_filename(self):
        return str(self.profile_image)[str(self.profile_img).index(f'profile_images/{self.pk}/'):]

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

src/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login

from users.models import User

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=40, help_text="Required. Add a valid email address.")

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')

    # clean functions
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            # exception is thrown if no matching objects found
            return email
        raise forms.ValidationError(f"{email} is already in use. Please use another email.")

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            # exception is thrown if no matching object found
            return username
        raise forms.ValidationError(f"{username} is already in use. Please use another username.")

class UserAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("email", "password")

    def save(self, request):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Your email or password is incorrect.")


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'username', 'profile_img')
    
    # clean functions
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            # exception is thrown if no matching objects found
            return email
        raise forms.ValidationError(f"{email} is already in use. Please use another email.")

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            # exception is thrown if no matching object found
            return username
        raise forms.ValidationError(f"{username} is already in use. Please use another username.")

    def save(self, commit=True):
        user = super(UserUpdateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']
        user.profile_img = self.cleaned_data['profile_img']
        if commit:
            user.save()
        return user

src/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from friends.friend_request_status import *
from friends.models import *
from friends.utils import *
from users.forms import UserRegistrationForm, UserAuthenticationForm, UserUpdateForm
from users.models import *
import os

def registration_view(request, *args, **kwargs):
    curr_user = request.user

    if curr_user.is_authenticated:
        return HttpResponse(f"You are already logged in as {curr_user.email}.")
    context = {}

    if request.POST:
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email').lower()
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            login(request, user)
            FriendList.objects.create(user=user)
            return redirect("home")
        else:
            context['registration_form'] = form
    else:
        form = UserRegistrationForm()
        context['registration_form'] = form
    return render(request, 'users/register.html', context)

def logout_view(request):
    logout(request)
    return redirect("home")

def login_view(request, *args, **kwargs):
    context = {}
    curr_user = request.user
    if curr_user.is_authenticated:
        return redirect("home")
    if request.POST:
        form = UserAuthenticationForm(request.POST)
        
        if form.is_valid():
            form.save(request)
            return redirect("home")
        else:
            context['login_form'] = form
    return render(request, "users/login.html", context)

def profile_view(request, *args, **kwargs):
    context = {}
    userid = kwargs.get("user_id")
    try:
        viewed_user = User.objects.get(pk=userid)
    except User.DoesNotExist:
        return HttpResponse("No user of this id found.")
    if User:
        context['id'] = viewed_user.id
        context['email'] = viewed_user.email
        context['username'] = viewed_user.username
        context['profile_img'] = viewed_user.profile_img.url
        
        try:
            friend_list = FriendList.objects.get(user=viewed_user)
        except FriendList.DoesNotExist:
            friend_list = FriendList(user=viewed_user)
            friend_list.save()
        friends = friend_list.friends.all()
        context['friends'] = friends

        is_self = True
        is_friend = False
        curr_user = request.user
        friend_requests = None
        request_sent = FriendRequestStatus.NO_FRIEND_REQUEST.value
        # NO_FRIEND_REQUEST = 0
        # FRIEND_REQUEST_TO_USER = 1
        # FRIEND_REQUEST_FROM_USER = 2
        if (curr_user.is_authenticated and curr_user != viewed_user):
            is_self = False
            if friends.filter(pk=curr_user.id):
                is_friend = True
            else:
                is_friend = False
                if friend_request_exists(sender=viewed_user, receiver=curr_user) != False:
                    request_sent = FriendRequestStatus.FRIEND_REQUEST_TO_USER.value
                    context['pending_friend_request_id'] = friend_request_exists(sender=viewed_user, receiver=curr_user).id
                elif friend_request_exists(sender=curr_user, receiver=viewed_user) != False:
                    request_sent = FriendRequestStatus.FRIEND_REQUEST_FROM_USER.value
                else:
                    request_sent = FriendRequestStatus.NO_FRIEND_REQUEST.value
        elif not curr_user.is_authenticated:
            is_self = False
        else:
            try:
                friend_requests = FriendRequest.objects.filter(receiver=curr_user, pending=True)
            except:
                pass

        context['is_self'] = is_self
        context['is_friend'] = is_friend
        context['BASE_URL'] = settings.BASE_URL
        context['request_sent'] = request_sent
        context['friend_requests'] = friend_requests

        return render(request, "users/profile.html", context)

def user_search_view(request, *args, **kwargs):
    context = {}
    curr_user = request.user
    if request.method == "GET":
        search_query = request.GET.get("q")
        if len(search_query) > 0:
            search_results = User.objects.filter(username__icontains=search_query)
            profiles = []
            if curr_user.is_authenticated:
                curr_user_friend_list = FriendList.objects.get(user=curr_user)
                for user in search_results:
                    profiles.append((user, curr_user_friend_list.is_mutual_friend(user)))
                context['profiles'] = profiles
            else:
                for user in search_results:
                    profiles.append((user, False))
                context['profiles'] = profiles
    return render(request, "users/user_search.html", context)

def edit_user_view(request, *args, **kwargs):
    if not request.user.is_authenticated:
        return redirect("login")
    user_userid = kwargs.get("user_id")
    try:
        user = User.objects.get(pk=user_userid)
    except User.DoesNotExist:
        return HttpResponse("An error occurred.")
    if user.pk != request.user.pk:
        return HttpResponse("Unable to edit another user's profile.")
    
    context = {}
    if request.POST:
        form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        image_updated = False
        # retrieve file if it exists
        if 'profile_image_file_selector' in request.FILES:
            request_file = request.FILES['profile_image_file_selector'] 
            # default path of settings.MEDIA_ROOT
            url = os.path.join(settings.MEDIA_ROOT + "/", str(user.pk))
            fss = FileSystemStorage(location=url)
            user.profile_img.delete()
            file = fss.save("profile_image.png", request_file)
            user.profile_img = f"{str(user.pk)}/profile_image.png"
            user.save()
            image_updated = True
        if form.is_valid():
            form.save()
            return redirect("user_app:user_profile", user_id=user.pk)
        elif image_updated:
            return redirect("user_app:user_profile", user_id=user.pk)
        else:
            form = UserUpdateForm(request.POST, instance=request.user,
                initial = {
                    "id": user.pk,
                    "email": user.email,
                    "username": user.username,
                    "profile_img": user.profile_img,
                }
            )
            context['form'] = form
    else:
        form = UserUpdateForm(
            initial = {
                "id": user.pk,
                "email": user.email,
                "username": user.username,
                "profile_img": user.profile_img,
            }
        )
        context['form'] = form
    context['max_upload_memory_size'] = settings.DATA_UPLOAD_MAX_MEMORY_SIZE
    return render(request, "users/edit_user.html", context)

src/users/templates/users/edit_user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	.image-container{
		max-width: 250px;
		height: auto;
		position: relative;
	}
	.field-heading{
		color: #737373;
	}
	#id_confirm{
		color: green;
	}
	#id_confirm:hover {
		opacity: 0.3;
	}
	#id_cancel:hover {
		opacity: 0.3;
	}
	#id_cancel{
		color: red;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.btn{
		background-color: var(--btn-color);
		border: none;
		width: 100%;
	}
	.btn:hover{
		background-color: var(--btn-color-hover);
	}
	.profile-image{
		max-width: 250px;
		max-height: 250px;
		min-width: 250px;
		min-height: 250px;
	}
</style>

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card profile-card">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<!-- <div class="mb-2" id="confirm_image_upload"> -->
		  			<!-- <span id="cancel_changes" class="material-icons">cancel</span>
		  			<span id="confirm_changes" class="material-icons">check</span> -->
		  		<!-- </div> -->
		  		<div class="image-container" id="id_image_container">
	  				<img class="border border-dark rounded-circle img-fluid mx-auto profile-image" id="profile_image" src="{{form.initial.profile_img.url}}" alt="Default Profile Image">
					<!-- <div class="middle" id="id_middle_container"></div> -->
					<button class="mt-4 btn btn-primary flex-grow-1" type="button" id="upload-image-btn">Upload Image</button>
					<!-- <div class="text" id="id_text">Edit</div> -->
		  		</div>
		  		<form class="form-signin" method="post" enctype="multipart/form-data">{% csrf_token %}
		  			<input class="d-none" type="file" id="id_profile_image_file_selector" name="profile_image_file_selector" onchange="readURL(this)">
			  		<h6 class="mt-4 field-heading">Email</h6>
			  		<input type="email" name="email" id="id_input_email" class="form-control" placeholder="Email address" required autofocus value={{form.initial.email}}>
			  		<h6 class="mt-4 field-heading">Username</h6>
			  		<input type="text" name="username" id="id_input_username" class="form-control" placeholder="Username" required value="{{form.initial.username}}">
					<!-- <div class="mt-4 checkbox">
						<label>
							<input type="checkbox" name="hide_email" id="id_input_hide_email" {% if form.initial.hide_email %}checked{%endif%}>
							Hide Email
						</label>
					</div> -->

					{% for field in form %}
					<p>
					{% for error in field.errors %}
					<p style="color: red">{{ error }}</p>
					{% endfor %}
					</p>
					{% endfor %}
					{% if form.non_field_errors %}
					<div style="color: red">
					<p>{{form.non_field_errors}}</p>
					</div>
					{% endif %}

					<div class="d-flex flex-column mt-4">
						<button class="mt-4 btn btn-primary flex-grow-1" type="submit">Save</button>
					</div>
				</form>
		  	</div>
		  </div>
		</div>
	</div>
</div>


<script type="text/javascript">
	function readURL(inputImage){
		if (inputImage.files && inputImage.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
            	// disableImageOverlay()
            	var image = e.target.result
            	var imageField = document.getElementById('profile_image')
                imageField.src = image
            };

            reader.readAsDataURL(inputImage.files[0]);
		}
	}
	// var uploadConfirm = document.getElementById("confirm_image_upload");
	// uploadConfirm.classList.remove("d-flex");
	// uploadConfirm.classList.remove("flex-row");
	// uploadConfirm.classList.remove("justify-content-between");
	// uploadConfirm.classList.add("d-none");
	
	// upload button
	document.getElementById("upload-image-btn").addEventListener("click", function(){
		document.getElementById("id_profile_image_file_selector").click();
		
		// var uploadConfirm = document.getElementById("confirm_image_upload");
		// uploadConfirm.classList.add("d-flex");
		// uploadConfirm.classList.add("flex-row");
		// uploadConfirm.classList.add("justify-content-between");
		// uploadConfirm.classList.remove("d-none");	
	});
	
	// confirm changes button
	// document.getElementById("confirm_changes").addEventListener("click", function(event){
		// uploadConfirm.classList.remove("d-flex");
		// uploadConfirm.classList.remove("flex-row");
		// uploadConfirm.classList.remove("justify-content-between");
		// uploadConfirm.classList.add("d-none");
	// })
	// document.getElementById("cancel_changes").addEventListener("click", function(event){
	// 	window.location.reload();
	// })

</script>


{% endblock content %}

src/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style type="text/css">
.login-card {
    width: 100%;
    height: 100%;
    max-width: 80vw;
    max-height: 75vh;
    margin-top: 5vh;
}
.card-body{
    margin: 5vh 20vw;
    align-items: center;
}
.login-form input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
}
.login-form input[type="password"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
.title-text{
    text-align: center;
}
.btn{
    background-color: var(--btn-color);
    border: none;
}
.btn:hover{
    background-color: var(--btn-color-hover);
}
</style>

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card login-card">
		  <div class="card-body">
		    <form class="login-form" method="post">{% csrf_token %}
				<!-- <div class="d-flex flex-column pb-3">
				<img class="img-fluid mx-auto d-block" src="{% static 'codingwithmitch/logo_250_250_transparent.png' %}" alt="codingwithmitch logo" width="72" height="72">
				</div> -->
                <h3 class="title-text">Log In</h3> 
				<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

				<input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>

				{% for field in login_form %}
				<p>
				{% for error in field.errors %}
				<p style="color: red">{{ error }}</p>
				{% endfor %}
				</p>
				{% endfor %}
				{% if login_form.non_field_errors %}
				<div style="color: red">
				<p>{{login_form.non_field_errors}}</p>
				</div>

				{% endif %}

				<button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
				</form>
		  </div>
		</div>
		
	</div>
</div>

{% endblock content %}

src/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	.profile-card{
		max-height: 80vh;
	}
	.image-container{
		max-width: 250px;
		height: auto;
	}
	.profile-image{
		max-width: 250px;
		max-height: 250px;
		min-width: 250px;
		min-height: 250px;
	}
	.field-heading{
		color: var(--secondary-text-color);
	}
	.icon-container:hover {
		opacity: 0.3;
		cursor: pointer;
	}
	.friends-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.person-add-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.friend-text{
		font-weight: 500;
		color: black;
	}
	.friends-btn{
		background-color: #cccccc;
		border-color: #cccccc;
		color: #000;
		font-weight: 500;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.card{
		border-radius: 12px;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.confirm-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request:hover {
		opacity: 0.3;
	}
	.message-btn-text{
		font-weight: 500;
	}
	.btn{
		background-color: var(--btn-color);
		border: none;
		width: 100%;
	}
	.btn:hover{
		background-color: var(--btn-color-hover);
	}
</style>

<div class="container-fluid">
	<div class="d-flex flex-row justify-content-center flex-wrap align-items-start">
		<div class="card profile-card m-2">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<div class="image-container mx-auto mb-4">
		  			<img class="d-block border border-dark rounded-circle img-fluid mx-auto profile-image" alt="profile image" id="id_profile_image" src="{{profile_img}}">
		  		</div>
		  		<p class="mt-4 mb-1 field-heading">Email</p>
		  		{%  if is_self %}
		  			<h5>{{email}}</h5>
		  		{% else %}
			  	    <h5>**********</h5>
			  	{% endif %}
		  		<p class="mt-4 mb-1 field-heading">Username</p>
		  		<h5>{{username}}</h5>

				{% if is_self %}
				<a class="mt-4 btn btn-primary" href="{% url 'user_app:edit_user' user_id=id %}">Update</a>
				<div class="d-flex flex-column mt-4"></div>
				{% endif %}

		  	</div>
		  </div>
		</div>

		{% if request.user.is_authenticated %}
		<div class="d-flex flex-column mb-4">

			<!-- THEM to YOU -->
			{% if request_sent == 1 %}
			<div class="card m-2 p-4">
				<div class="d-flex flex-row align-items-center">
					<span class="friend-text align-items-center mr-2">Accept Friend Request</span>
					<span id="id_cancel_{{id}}" class="decline-friend-request material-icons p-1" onclick='triggerDeclineFriendRequest("{{pending_friend_request_id}}")'>cancel</span>
  					<span id="id_confirm_{{id}}" class="confirm-friend-request material-icons p-1" onclick='triggerAcceptFriendRequest("{{pending_friend_request_id}}")'>check</span>
				</div>
			</div>
			{% endif %}

			<div class="card m-2 px-4 pb-4">
				<!-- Cancel Friend Request / Send Friend Request / Remove Friend -->
				{% if is_friend == False and is_self == False %}
						<!-- You sent them a request -->
						{% if request_sent == 2 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-danger" id="id_cancel_friend_request_btn">
								Cancel Friend Request
							</button>
						</div>
						{% endif %}
						<!-- No requests have been sent -->
						{% if request_sent == 0 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-primary" id="id_send_friend_request_btn">
								Send Friend Request
							</button>
						</div>
						{% endif %}
				{% endif %}
					
					
				{% if is_friend %}
					<div class="dropdown pt-4 m-auto">
						<button class="btn btn-secondary dropdown-toggle friends-btn" type="button" id="id_friends_toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Friends
						</button>
						<div class="dropdown-menu" aria-labelledby="id_friends_toggle">
							<a class="dropdown-item" href="#" onclick="removeFriend('{{id}}', onFriendRemoved)">Unfriend</a>
						</div>
					</div>
				{% endif %}
				
				<!-- Friend list link -->
		  		<div class="d-flex flex-column pt-4">
					<a href="{% url 'friend_app:friend_list' user_id=id %}">
						<div class="d-flex flex-row align-items-center justify-content-center icon-container">
							<span class="material-icons mr-2 friends-icon">contact_page</span><span class="friend-text">Friends ({{ friends|length }})</span>
						</div>
					</a>
				</div>
			</div>

			{% if friend_requests %}
			<div class="card m-2 px-4 pb-4">
				<!-- Friend requests -->
		  		<div class="d-flex flex-column pt-4">
					<a href="{% url 'friend_app:friend_request_list' user_id=id %}">
						<div class="d-flex flex-row align-items-center justify-content-center icon-container">
							<span class="material-icons mr-2 person-add-icon">person_add</span><span class="friend-text">Friend Requests ({{ friend_requests|length }})</span>
						</div>
					</a>
				</div>
			</div>
			{% endif %}

			{% if is_friend %}
			<a href="{% url 'friendchat:friend_chat' friend_id=id %}">
				<div class="d-flex flex-row align-items-center btn btn-primary m-2 px-4">
					<span class="material-icons m-auto">
					message
					</span>
					<span class="message-btn-text m-auto pl-2">Message</span>
				</div>
			</a>
			{% endif %}

		</div>
		{% endif %}

	</div>
</div>


<script type="text/javascript">

	function onFriendRequestSent(){
		location.reload();
	}

	function onFriendRequestCancelled(){
		location.reload();
	}

	function onFriendRemoved(){
		location.reload();
	}

	function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}

	var sendFriendRequestBtn = document.getElementById("id_send_friend_request_btn")
	if (sendFriendRequestBtn != null){
		sendFriendRequestBtn.addEventListener("click", function(){
			sendFriendRequest("{{id}}", onFriendRequestSent)
		})
	}

	var cancelFriendRequestBtn = document.getElementById("id_cancel_friend_request_btn")
	if(cancelFriendRequestBtn != null){
		cancelFriendRequestBtn.addEventListener("click", function(){
			cancelFriendRequest("{{id}}", onFriendRequestCancelled)
		})
	}

	var removeFriendBtn = document.getElementById("id_unfriend_btn")
	if (removeFriendBtn != null){
		removeFriendBtn.addEventListener("click", function(){
			removeFriend("{{id}}", onFriendRemoved)
		})
	}

	function triggerAcceptFriendRequest(friend_request_id){
		acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}
	
</script>

{% include 'friends/send_friend_request.html' %}
{% include 'friends/accept_friend_request.html' %}
{% include 'friends/decline_friend_request.html' %}
{% include 'friends/cancel_friend_request.html' %}
{% include 'friends/remove_friend.html' %}

{% endblock content %}