src/SocialNetApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from users import views as uviews
from userposts import views as upviews


urlpatterns = [
    path('', upviews.home_page, name='home'),
    path('admin/', admin.site.urls),
    path('chat/', include('friendchat.urls')),
    path('friend/', include('friends.urls', namespace="friends")),
    path('login/', uviews.login_view, name="login"),
    path('logout/', uviews.logout_view, name="logout"),
    path('profile/', include('users.urls', namespace="profile")),
    path('register/', uviews.registration_view, name="register"),
    path('search/', uviews.user_search_view, name="search"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/friendchat/urls.py
from django.urls import path
from friendchat import views as fcviews
from django.conf.urls.static import static
from django.conf import settings

app_name = "friendchat"

urlpatterns = [
    path('', fcviews.chat_list_view, name="friend_chat_list"),
    path('<friend_id>/', fcviews.chat_view, name='friend_chat'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/friendchats/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from friendchats import views as fcviews

app_name = "friendchat_app"

urlpatterns = [
    path('<str:room_name>/', fcviews.chatroom_view, name="chat_room"),
    path('chat_list/<user_id>', fcviews.chatroom_list_view, name="chat_list"),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path
from users import views as uview
from django.conf.urls.static import static
from django.conf import settings
from . import api

app_name = "user_app"

urlpatterns = [
    path('<user_id>/', uview.profile_view, name="user_profile"),
    path('<user_id>/edit/', uview.edit_user_view, name="edit_user"),
    path('api/user/', api.CreateUser.as_view(), name='create_user_api'), 
    path('api/user/<int:pk>/', api.UserDetail.as_view(), name='user_detail_api'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/friendchat/models.py
from django.db import models
from django.db.models import Count
from django.conf import settings

class ChatManager(models.Manager):
    def get_or_create_personal_channel(self, user1, user2):
        channels = self.get_queryset()
        channels = channels.filter(users__in=[user1, user2]).distinct()
        channels = channels.annotate(u_count=Count('users')).filter(u_count=2)
        if channels.exists():
            return channels.first()
        else:
            users = sorted( [ user1.email.split('@')[0], user2.email.split('@')[0] ] )
            if users[0] == user1.email.split('@')[0]:
                channel_name = f"{user1.pk}{user1.email.split('@')[0]}{user2.pk}{user2.email.split('@')[0]}"
            else:
                channel_name = f"{user2.pk}{user2.email.split('@')[0]}{user1.pk}{user1.email.split('@')[0]}"
            channel = self.create(name=channel_name)
            channel.users.add(user1)
            channel.users.add(user2)
            return channel

    def by_user(self, user):
        return self.get_queryset().filter(users__in=[user])

class TrackingModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Channel(TrackingModel):
    name = models.CharField(max_length=50, null=True, blank=True)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL)

    objects = ChatManager()

    def __str__(self) -> str:
        if self.users.count() == 2:
            return f'{self.users.first()} and {self.users.last()}'
        return f'{self.name}'

class Message(TrackingModel):
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(blank=False, null=False)

    def __str__(self) -> str:
        return f'From <Channel - {self.channel}>'

src/friendchats/models.py
from django.db import models
from django.conf import settings

class ChatRoom(models.Model):
    chatroom_name = models.CharField(max_length=255, unique=True, blank=True)
    participant1 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    participant2 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class ChatLog(models.Model):
    chatlog = models.TextField(unique=False, blank=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    chatroom = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)

#     def __str__(self):
#         return self.chatroom_name
    
#     def connect_user(self, users_to_add):
#         # users_to_add includes request user and user's friend
#         user_added = False
#         if not user_to_add in self.participants.all():
#             self.participants.add(user_to_add)
#             self.save()
#             user_added = True
#         elif user_to_add in self.participants.all():
#             user_added = True
#         return user_added

# class ChatList(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user")
#     chatrooms = models.ManyToManyField(ChatRoom, blank=True, related_name="chatrooms")

#     def __str__(self):
#         return self.user.username

#     def create_chat(self, user_to_add):
#         chat_room_id = f"{str(int(self.user.id) * 4 - 4)}{str(int(user_to_add.id) * 3 - 5)}chatroom{self.user.username}"
#         if not chat_room_id in self.chatrooms.all():
#             self.chatrooms.add(chat_room_id)
#         pass
        
#         # if not user_to_add in self.friends.all():
#         #     self.friends.add(user_to_add)
    
#     def delete_chat(self, user_to_remove):
#         pass
#         # if user_to_remove in self.friends.all():
#         #     self.friends.remove(user_to_remove)

#     # def unfriend(self, user_to_remove):
#     #     self.remove_friend(user_to_remove)

#     #     removed_user = FriendList.objects.get(user=user_to_remove)
#     #     # removed_user.remove_user(self.user)
#     #     removed_user.remove_friend(self.user)

src/friendchat/views.py
from django.shortcuts import render
from django.http import HttpResponse
from friendchat.models import Channel, Message
from friends.models import FriendList
from users.models import User

def chat_list_view(request, *args, **kwargs):
    context = {}
    curr_user = request.user
    if not curr_user.is_authenticated:
        return HttpResponse("You must be logged in to chat with other users")

    friend_chat_list = []
    friends = FriendList.objects.get(user=curr_user)
    for friend in friends.friends.all():
        channel = Channel.objects.filter(users__in=[friend]).filter(users__in=[curr_user]).first()
        try:
            latest_message = Message.objects.filter(channel=channel).order_by('-pk').first().content
        except:
            latest_message = ''
        friend_chat_list.append([friend, latest_message])
    context['friend_chat_list'] = friend_chat_list
    return render(request, "friendchat/chatlist.html", context=context)

def chat_view(request, *args, **kwargs):
    context = {}
    curr_user = request.user
    if not curr_user.is_authenticated:
        return HttpResponse("You must be logged in to chat with other users")
    friend_id  = kwargs.get("friend_id")
    friend = User.objects.get(pk=friend_id)
    channel = Channel.objects.get_or_create_personal_channel(curr_user, friend)
    if channel == None:
        raise HttpResponse("An error occurred, could not send message")
    context['friend'] = friend
    context['room_name'] = channel.name
    context['channel'] = channel
    context['sender'] = curr_user.pk
    context['messages'] = Message.objects.filter(channel=channel)
    if request.method == "POST":
        content = request.POST.get("message")
        Message.objects.create(sender=curr_user, channel=channel, content=content)
        context['channel'] = channel
        context['messages'] = Message.objects.filter(channel=channel)
    return render(request, 'friendchat/chatroom.html', context)

src/friendchats/views.py
from django.shortcuts import render
from django.db.models import Q
from friendchats.models import ChatRoom

def chatroom_list_view(request, *args, **kwargs):
    context = {}
    curr_user = request.user
    curr_user_chatrooms = ChatRoom.objects.filter(Q(participant1=curr_user) | Q(participant2=curr_user))
    context['chatrooms'] = curr_user_chatrooms
    return render(request, 'friendchats/friend_chat_list.html', context)

def chatroom_view(request, *args, **kwargs):
    context = {}
    curr_user = request.user
    # context['room_name'] = kwargs.get("room_name")

    return render(request, 'friendchats/friend_chat.html', context)

src/friendchats/templates/friendchats/friend_chat.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
</div>

<script>
    const roomName = JSON.parse(document.getElementById('room-name').textContent);

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + roomName
        + '/'
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        document.querySelector('#chat-log').value += (data.message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));
        messageInputDom.value = '';
    };
</script>
{% endblock content %}

src/friendchats/templates/friendchats/friend_chat_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    {% if chatrooms %}
	<!-- <div class=""> -->
	{% for chatroom in chatrooms %}
	<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
		{% if chatroom.participant1 == request.user %}
		<a class="profile-link" href="{% url 'user_app:user_profile' user_id=chatroom.participant2.id %}">
			<div class="card-image m-2">
				<img class="img-fluid profile-image" src="{{chatroom.participant2.profile_img.url}}" alt="">
			</div>
		</a>
		<a class="profile-link" href="{% url 'user_app:user_profile' user_id=chatroom.participant2.id %}">
			<div class="card-center px-2">
				<h4 class="card-title">{{chatroom.participant2.username}}</h4>
			</div>
		</a>
		{% else %}
		<a class="profile-link" href="{% url 'user_app:user_profile' user_id=chatroom.participant1.id %}">
			<div class="card-image m-2">
				<img class="img-fluid profile-image" src="{{chatroom.participant1.profile_img.url}}" alt="">
			</div>
		</a>
		<a class="profile-link" href="{% url 'user_app:user_profile' user_id=chatroom.participant1.id %}">
			<div class="card-center px-2">
				<h4 class="card-title">{{chatroom.participant1.username}}</h4>
			</div>
		</a>
		{% endif %}
		<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
			<a class="chat-link" href="{% url 'friendchat_app:chat_room' room_name=chatroom.chatroom_name %}">
				<div class="d-flex flex-row friends-text-container p-3">
					<p class="friends-text m-auto">
						Open Chat
					</p>
					<span class="material-icons m-auto pl-2">
					person_pin
					</span>
				</div>				
			</a>
		</div>
	</div>
	{% endfor %}
	
	{% else %} <!-- If no chats -->
	<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
		<p>No chats</p>
	</div>
	{% endif %}
</div>

<!-- <script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };

    document.querySelector('#room-name-submit').onclick = function(e) {
        var roomName = document.querySelector('#room-name-input').value;
        window.location.pathname = '/chat/' + roomName + '/';
    };
</script> -->
{% endblock content %}